config/routes.rb
Rails.application.routes.draw do
	# Home route.
  root to: "home#index"

  get "posts/show" => "singles#show"
  get "documents" => "pages#documents", as: :documents
  get "posts/show/:slug" => "posts#show", as: :show_post

  # Custom user.
   
  get "/users"     => "custom_users#users_and_permissions", as: :all_users 
  get "/users/unregistered"     => "custom_users#unregistered", as: :unregistered_commission_percentage 
  post "/users/new"     => "custom_users#create", as: :create_user
  get "/users/new"     => "custom_users#new", as: :new_user
  get "/user/edit/:id" => "custom_users#edit", as: :edit_user
  patch "/user/update/:id" => "custom_users#update", as: :udapte_user
  delete "/user/destroy/:id" => "custom_users#destroy", as: :destroy_user
  get "/user/delete/:id" => "custom_users#delete", as: :delete_user
   
  resources :posts do 
    get "delete"
  end

  resources :post_types do 
    get "delete"
  end

  resources :post_categories do 
    get "delete"
  end
  #devise_for :users
  resources :permission_roles do 
    get "delete"
  end
  resources :permissions do 
    get "delete"
  end
  resources :roles do 
    get "delete"
  end


  get "/dashboard" => "dashboard#index" , as: :dashboard
   
   
   
   
     
     devise_for :users, path: '', controllers: { 
       registrations: "users/registrations",
       confirmations: 'users/confirmations',
       passwords: "users/passwords",
       sessions: "users/sessions"
           
       }, 
       path_names: {
           sign_in: 'login', 
           sign_out: 'logout', 
           password: 'secret', 
           confirmation: 'verification', 
           unlock: 'unblock', 
           registration: 'signup', 
           sign_up: '' 
       }
      
     #root 'config_options#new'
     devise_scope :user do
       root to: "users/sessions#new"
       authenticated :user do
         root 'dashboard#index', as: :authenticated_root
       end
   
       unauthenticated do
         root 'users/sessions#new', as: :unauthenticated_root
       end
     end
   
   
     # Dynamic error pages
     get "/404", to: "errors#not_found"
     get "/422", to: "errors#unacceptable"
     get "/500", to: "errors#internal_error"
     mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	
	before_action :authenticate_user!
	
	layout 'dashboard'
	
	def index
		

		
	end

	def unauthorize
		render layout: 'unauthorize'
	end

	


	
	

end

app/views/layouts/partials/dashboard/navs/_customer-nav.html.erb
<!-- ########## START: LEFT PANEL ########## -->

      <ul class="br-sideleft-menu">
       <li class="br-menu-item">
          <%= link_to  raw('<i class="fa fa-home tx-20"></i> <span class="menu-item-label">Tableau de bord</span>'), dashboard_path, class: "br-menu-link active" %>
        </li><!-- br-menu-item -->

       

        <li class="br-menu-item">
          <a href="#" class="br-menu-link with-sub">
            <i class="fa fa-money tx-20"></i>
            <span class="menu-item-label">Opérations</span>
          </a><!-- br-menu-link -->
          <ul class="br-menu-sub">
            
            <li class="sub-item">
                <%= link_to  "Dépots", deposits_path, class: "sub-link" %>
            </li>

            <li class="sub-item">
                <%= link_to  "Retraits", withdrawals_path, class: "sub-link" %>
            </li>

            <li class="sub-item">
                <%= link_to  "Transferts", transfers_path, class: "sub-link" %>
            </li>

           

          </ul>
        </li>


        

       <li class="br-menu-item">
          <a href="#" class="br-menu-link with-sub">
            <i class="fa fa-bar-chart tx-20"></i>
            <span class="menu-item-label">Situations</span>
          </a><!-- br-menu-link -->
          <ul class="br-menu-sub">
            
            <li class="sub-item">
                <%= link_to  "Mon solde", my_balance_path, class: "sub-link" %>
            </li>

            
          </ul>
        </li>

        
        
       
      </ul><!-- br-sideleft-menu -->

      
       
        
      </div><!-- info-list -->

    <!-- ########## END: LEFT PANEL ########## -->

app/views/layouts/partials/dashboard/navs/_guest-nav.html.erb
<!-- ########## START: LEFT PANEL ########## -->

      <ul class="br-sideleft-menu">
       <li class="br-menu-item">
          <%= link_to  raw('<i class="fa fa-home tx-20"></i> <span class="menu-item-label">Tableau de bord</span>'), dashboard_path, class: "br-menu-link active" %>
        </li><!-- br-menu-item -->

        <li class="br-menu-item">
          <%= link_to  raw('<i class="fa fa-home tx-20"></i> <span class="menu-item-label">Courrier d\'arrivée</span>'), arrival_mails_path, class: "br-menu-link" %>
        </li><!-- br-menu-item -->

        <li class="br-menu-item">
          <%= link_to  raw('<i class="fa fa-home tx-20"></i> <span class="menu-item-label">Courrier départ</span>'), departure_mails_path, class: "br-menu-link" %>
        </li><!-- br-menu-item -->



       



         
        
        <li class="br-menu-item">
          <a href="#" class="br-menu-link with-sub">
            <i class="fa fa-cogs tx-20"></i>
            <span class="menu-item-label">Paramètres</span>
          </a><!-- br-menu-link -->
          <ul class="br-menu-sub">
            
            <li class="sub-item">
                <%= link_to  "Utilisateurs", root_path, class: "sub-link" %>
            </li>

            <li class="sub-item">
                <%= link_to  "Types registre", registry_types_path, class: "sub-link" %>
            </li>

            <li class="sub-item">
                <%= link_to  "Registres", registries_path, class: "sub-link" %>
            </li>
             <li class="sub-item">
                <%= link_to  "Services", services_path, class: "sub-link" %>
            </li>
            <li class="sub-item">
                <%= link_to  "Supports", supports_path, class: "sub-link" %>
            </li>
            <li class="sub-item">
                <%= link_to  "Natures", natures_path, class: "sub-link" %>
            </li>

            <li class="sub-item">
                <%= link_to  "Types correspondant", correspondent_types_path, class: "sub-link" %>
            </li>

            <li class="sub-item">
                <%= link_to  "Domaines d'activité", activity_fields_path, class: "sub-link" %>
            </li>

            <li class="sub-item">
                <%= link_to  "Correspondants", correspondents_path, class: "sub-link" %>
            </li>

          </ul>
        </li>
       
      </ul><!-- br-sideleft-menu -->

      
       
        
      </div><!-- info-list -->

    <!-- ########## END: LEFT PANEL ########## -->

app/views/layouts/partials/dashboard/navs/_patient-nav.html.erb
<!-- ########## START: LEFT PANEL ########## -->

      <ul class="br-sideleft-menu">
       <li class="br-menu-item">
          <%= link_to  raw('<i class="fa fa-home tx-20"></i> <span class="menu-item-label">Tableau de bord</span>'), dashboard_path, class: "br-menu-link active" %>
        </li><!-- br-menu-item -->

       
        <li class="br-menu-item">
          <a href="#" class="br-menu-link with-sub">
            <i class="fa fa-calendar tx-20"></i>
            <span class="menu-item-label">Rendez-vous</span>
          </a><!-- br-menu-link -->
          <ul class="br-menu-sub">
            
          
            <li class="sub-item">
                <%= link_to  "Mes rendez-vous", appointments_path, class: "sub-link" %>
            

          </ul>
        </li>
       
        

        <li class="br-menu-item">
            <a href="#" class="br-menu-link with-sub">
              <i class="fa fa-shopping-cart tx-20"></i>
              <span class="menu-item-label">Mes commandes</span>
            </a><!-- br-menu-link -->
            <ul class="br-menu-sub">
              
            
              <li class="sub-item">
                  <%= link_to  "Médicaments", medicament_orders_path, class: "sub-link" %>
              </li>
              

            </ul>
          </li>
        

        

        
        <li class="br-menu-item">
            <a href="#" class="br-menu-link with-sub">
              <i class="fa fa-stethoscope tx-20"></i>
              <span class="menu-item-label">Consultations</span>
            </a><!-- br-menu-link -->
            <ul class="br-menu-sub">
              
            
              <li class="sub-item">
                  <%= link_to  "Consultations en ligne", advices_path, class: "sub-link" %>
              </li>
              

            </ul>
          </li>


        
      </ul><!-- br-sideleft-menu -->

      
       
        
      </div><!-- info-list -->

    <!-- ########## END: LEFT PANEL ########## -->

app/views/layouts/partials/dashboard/navs/_prestataire-nav.html.erb
<!-- ########## START: LEFT PANEL ########## -->

      <ul class="br-sideleft-menu">
       <li class="br-menu-item">
          <%= link_to  raw('<i class="fa fa-home tx-20"></i> <span class="menu-item-label">Tableau de bord</span>'), dashboard_path, class: "br-menu-link active" %>
        </li><!-- br-menu-item -->

        <li class="br-menu-item">
          <%= link_to  raw('<i class="fa fa-building tx-20"></i> <span class="menu-item-label">Structures</span>'), structures_path, class: "br-menu-link" %>
        </li><!-- br-menu-item -->

        
        <% if is_structure_admin?() && structure_is?(current_structure.id, "Clinique") %>

          <li class="br-menu-item">
            <a href="#" class="br-menu-link with-sub">
              <i class="fa fa-calendar tx-20"></i>
              <span class="menu-item-label">Agenda</span>
            </a><!-- br-menu-link -->
            <ul class="br-menu-sub">
              
            
              <li class="sub-item">
                  <%= link_to  "Mes rendez-vous", appointments_path, class: "sub-link" %>
              </li>
              <li class="sub-item">
                  <%= link_to  "Mon programme", plannings_path, class: "sub-link" %>
              </li>

            </ul>
          </li>
        <% end %>

        <% if is_structure_admin?() && structure_is?(current_structure.id, "Laboratoire") %>
          <li class="br-menu-item">
            <a href="#" class="br-menu-link with-sub">
              <i class="fa fa-stethoscope tx-20"></i>
              <span class="menu-item-label">Analyses</span>
            </a><!-- br-menu-link -->
            <ul class="br-menu-sub">
              
            
              <li class="sub-item">
                  <%= link_to  "Liste des analyses", analyses_path, class: "sub-link" %>
                  <%= link_to  "Demandes d'analyse", analysis_requests_path, class: "sub-link" %>

              </li>
<!--
              <li class="sub-item">
                  <%= link_to  "Demandes d'analyses", analyses_path, class: "sub-link" %>
              </li>
-->             

            </ul>
          </li>
        <% end %>
        
        <% if is_structure_admin?() && structure_is?(current_structure.id, "Pharmacie") %>
          <li class="br-menu-item">
            <a href="#" class="br-menu-link with-sub">
              <i class="fa fa-medkit tx-20"></i>
              <span class="menu-item-label">Médicaments</span>
            </a><!-- br-menu-link -->
            <ul class="br-menu-sub">
              
            
              <li class="sub-item">
                  <%= link_to  "Liste des médicaments", medicaments_path, class: "sub-link" %>
              </li>
              

            </ul>
          </li>

          <li class="br-menu-item">
            <a href="#" class="br-menu-link with-sub">
              <i class="fa fa-shopping-cart tx-20"></i>
              <span class="menu-item-label">Mes commandes</span>
            </a><!-- br-menu-link -->
            <ul class="br-menu-sub">
              
            
              <li class="sub-item">
                  <%= link_to  "Médicaments", medicament_orders_path, class: "sub-link" %>
              </li>
              

            </ul>
          </li>


        <% end %>
        
        <% if is_structure_admin? && structure_is?(current_structure.id, "Clinique") %>

          <li class="br-menu-item">
                <a href="#" class="br-menu-link with-sub">
                  <i class="fa fa-stethoscope tx-20"></i>
                  <span class="menu-item-label">Consultations</span>
                </a><!-- br-menu-link -->
                <ul class="br-menu-sub">
                  
                
                  <li class="sub-item">
                      <%= link_to  "Consultations en ligne", advices_path, class: "sub-link" %>
                  </li>
                  

                </ul>
            </li>


            <li class="br-menu-item">
              <a href="#" class="br-menu-link with-sub">
                <i class="fa fa-user-md tx-20"></i>
                <span class="menu-item-label">Médecins</span>
              </a><!-- br-menu-link -->
              <ul class="br-menu-sub">
                
              
                <li class="sub-item">
                    <%= link_to  "Liste des médecins", doctors_path, class: "sub-link" %>
                </li>
                

              </ul>
            </li>
        <% end %>

        <% if is_from_kosante?(current_user) %>
          <li class="br-menu-item">
                <a href="#" class="br-menu-link with-sub">
                  <i class="fa fa-stethoscope tx-20"></i>
                  <span class="menu-item-label">Consultations</span>
                </a><!-- br-menu-link -->
                <ul class="br-menu-sub">
                  
                
                  <li class="sub-item">
                      <%= link_to  "Consultations en ligne", advices_path, class: "sub-link" %>
                  </li>
                  

                </ul>
            </li>


        <% end %>
        
        <% if is_structure_admin?  %>

 <li class="br-menu-item">
          <a href="#" class="br-menu-link with-sub">
            <i class="fa fa-cog tx-20"></i>
            <span class="menu-item-label">Paramètres</span>
          </a><!-- br-menu-link -->
          <ul class="br-menu-sub">
            
          
            <li class="sub-item">
                <%= link_to  "Horaires d'ouverture", schedule_items_path, class: "sub-link" %>
            </li>



            

          </ul>
        </li>

<% end %>
       
      </ul><!-- br-sideleft-menu -->

      
       
        
      </div><!-- info-list -->

    <!-- ########## END: LEFT PANEL ########## -->

app/views/layouts/partials/dashboard/navs/_root-nav.html.erb
<!-- ########## START: LEFT PANEL ########## -->

      <ul class="br-sideleft-menu">
       <li class="br-menu-item">
          <%= link_to  raw('<i class="fa fa-home tx-20"></i> <span class="menu-item-label">Tableau de bord</span>'), dashboard_path, class: "br-menu-link active" %>
        </li><!-- br-menu-item -->

        <li class="br-menu-item">
          <%= link_to  raw('<i class="fa fa-home tx-20"></i> <span class="menu-item-label">Courrier d\'arrivée</span>'), arrival_mails_path, class: "br-menu-link" %>
        </li><!-- br-menu-item -->

        <li class="br-menu-item">
          <%= link_to  raw('<i class="fa fa-home tx-20"></i> <span class="menu-item-label">Courrier départ</span>'), departure_mails_path, class: "br-menu-link" %>
        </li><!-- br-menu-item -->



       



         
        
        <li class="br-menu-item">
          <a href="#" class="br-menu-link with-sub">
            <i class="fa fa-cogs tx-20"></i>
            <span class="menu-item-label">Paramètres</span>
          </a><!-- br-menu-link -->
          <ul class="br-menu-sub">
            
            <li class="sub-item">
                <%= link_to  "Utilisateurs", root_path, class: "sub-link" %>
            </li>

            <li class="sub-item">
                <%= link_to  "Types registre", registry_types_path, class: "sub-link" %>
            </li>

            <li class="sub-item">
                <%= link_to  "Registres", registries_path, class: "sub-link" %>
            </li>
             <li class="sub-item">
                <%= link_to  "Services", services_path, class: "sub-link" %>
            </li>
            <li class="sub-item">
                <%= link_to  "Supports", supports_path, class: "sub-link" %>
            </li>
            <li class="sub-item">
                <%= link_to  "Natures", natures_path, class: "sub-link" %>
            </li>

            <li class="sub-item">
                <%= link_to  "Types correspondant", correspondent_types_path, class: "sub-link" %>
            </li>

            <li class="sub-item">
                <%= link_to  "Domaines d'activité", activity_fields_path, class: "sub-link" %>
            </li>

            <li class="sub-item">
                <%= link_to  "Correspondants", correspondents_path, class: "sub-link" %>
            </li>

          </ul>
        </li>
       
      </ul><!-- br-sideleft-menu -->

      
       
        
      </div><!-- info-list -->

    <!-- ########## END: LEFT PANEL ########## -->

app/views/layouts/partials/dashboard/navs/_superuser-nav.html.erb
<!-- ########## START: LEFT PANEL ########## -->

      <ul class="br-sideleft-menu">
       <li class="br-menu-item">
          <%= link_to  raw('<i class="fa fa-home tx-20"></i> <span class="menu-item-label">Tableau de bord</span>'), dashboard_path, class: "br-menu-link active" %>
        </li><!-- br-menu-item -->

        

        <li class="br-menu-item">
          <a href="#" class="br-menu-link with-sub">
            <i class="fa fa-book tx-20"></i>
            <span class="menu-item-label">Articles</span>
          </a><!-- br-menu-link -->
          <ul class="br-menu-sub">
            
          
            <li class="sub-item">
                <%= link_to  "Catégories d'articles", post_categories_path, class: "sub-link" %>
            </li>
             <li class="sub-item">
                <%= link_to  "Articles", posts_path, class: "sub-link" %>
            </li>

          </ul>
        </li>

        


        <li class="br-menu-item">
          <a href="#" class="br-menu-link with-sub">
            <i class="fa fa-cog tx-20"></i>
            <span class="menu-item-label">Paramètres</span>
          </a><!-- br-menu-link -->
          <ul class="br-menu-sub">
            
          
            <li class="sub-item">
                <%= link_to  "Utilisateurs", all_users_path, class: "sub-link" %>
            </li>

            


          </ul>
        </li>
       
      </ul><!-- br-sideleft-menu -->

      
       
        
      </div><!-- info-list -->

    <!-- ########## END: LEFT PANEL ########## -->

app/views/layouts/partials/dashboard/navs/_user-nav.html.erb
<!-- ########## START: LEFT PANEL ########## -->

      <ul class="br-sideleft-menu">
       <li class="br-menu-item">
          <%= link_to  raw('<i class="fa fa-home tx-20"></i> <span class="menu-item-label">Tableau de bord</span>'), dashboard_path, class: "br-menu-link active" %>
        </li><!-- br-menu-item -->

        <li class="br-menu-item">
          <%= link_to  raw('<i class="fa fa-home tx-20"></i> <span class="menu-item-label">Courrier d\'arrivée</span>'), arrival_mails_path, class: "br-menu-link" %>
        </li><!-- br-menu-item -->

        <li class="br-menu-item">
          <%= link_to  raw('<i class="fa fa-home tx-20"></i> <span class="menu-item-label">Courrier départ</span>'), departure_mails_path, class: "br-menu-link" %>
        </li><!-- br-menu-item -->



       



         
        
        <li class="br-menu-item">
          <a href="#" class="br-menu-link with-sub">
            <i class="fa fa-cogs tx-20"></i>
            <span class="menu-item-label">Paramètres</span>
          </a><!-- br-menu-link -->
          <ul class="br-menu-sub">
            
            <li class="sub-item">
                <%= link_to  "Utilisateurs", root_path, class: "sub-link" %>
            </li>

            <li class="sub-item">
                <%= link_to  "Types registre", registry_types_path, class: "sub-link" %>
            </li>

            <li class="sub-item">
                <%= link_to  "Registres", registries_path, class: "sub-link" %>
            </li>
             <li class="sub-item">
                <%= link_to  "Services", services_path, class: "sub-link" %>
            </li>
            <li class="sub-item">
                <%= link_to  "Supports", supports_path, class: "sub-link" %>
            </li>
            <li class="sub-item">
                <%= link_to  "Natures", natures_path, class: "sub-link" %>
            </li>

            <li class="sub-item">
                <%= link_to  "Types correspondant", correspondent_types_path, class: "sub-link" %>
            </li>

            <li class="sub-item">
                <%= link_to  "Domaines d'activité", activity_fields_path, class: "sub-link" %>
            </li>

            <li class="sub-item">
                <%= link_to  "Correspondants", correspondents_path, class: "sub-link" %>
            </li>

          </ul>
        </li>
       
      </ul><!-- br-sideleft-menu -->

      
       
        
      </div><!-- info-list -->

    <!-- ########## END: LEFT PANEL ########## -->